version: '3'

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - db:/var/lib/mysql

  smtp:
    image: 'djfarrelly/maildev:1.1.0'
    command: 'bin/maildev --web 3080 --smtp 1025 --incoming-user smtp --incoming-pass smtp'
    ports:
      - '3080:3080'

  web: &rails
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -b '0.0.0.0'"
    volumes:
      - .:/app
      - bundle:/usr/local/bundle
    tmpfs: /app/tmp
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
    env_file: .env
    tty: true
    stdin_open: true

  redis:
    image: redis
    volumes:
      - redis:/data

  sidekiq:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app
    depends_on:
      - redis
      - smtp
    env_file:
      - .env
    command: bundle exec sidekiq

volumes:
  db:
  redis:
  bundle: